### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by krisidmisso**
fixes issue #27 

//I also had to clean .gradle in system user directory and project
```

rm -rf ~/.gradle/*
rm -rf android/.gradle
rm -rf node_modules/
npm install
cd android && ./gradlew clean

./gradlew assembleRelease

```

### CODE REVIEW

**Comment by Fkiesnh86** [comment]
It's not work

**npx react-native info**
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 2.90 GB / 15.87 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: 16.11.32802.440 (Visual Studio Community 2019), 17.3.32825.248 (Visual Studio Community 2022)
  Languages:
    Java: 16.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    `buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31`

**Comment by Fkiesnh86** [comment]
I have also tried to use latest buildToolsVersion but no luck.

`buildToolsVersion = "33.0.0"
    minSdkVersion = 21
    compileSdkVersion = 33
    targetSdkVersion = 33`

**Comment by Fkiesnh86** [comment]
It works if I update the build.gradle at the library folder manually. Please update the build.grade of master branch. Thanks.

**Comment by TronNatthakorn** [comment]
Please update to 1.2.1

**Pull request closed without merging**
